language: node_js
node_js:
- 10.15.3
cache:
  npm: true
  directories:
  - node_modules
before_script:
- npm run prepublish
script:
- npm run coverage

before_deploy:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
  - echo "@ts-simple:registry=https://registry.npmjs.org" >> $HOME/.npmrc 2> /dev/null

deploy:
  provider: script
    script: npm run lerna:publish
    skip_cleanup: true
    on:
      tags: true
      branch: master
