language: node_js
node_js:
- 10.15.3
cache:
  npm: true
  directories:
  - node_modules
before_script:
- npm run prepublish
script:
- npm run coverage

before_deploy:
  - npm config set @ts-simple:registry=https://registry.npmjs.org
  - npm config set //registry.npmjs.org/:_authToken=${NPM_TOKEN}
  - npm run lerna:badges

deploy:
  provider: script
  script: npm run lerna:publish
  skip_cleanup: true
  on:
    node: "10.15.3"
    tags: true
